// <auto-generated />
using System;
using CustomCharInfo.server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomCharInfo.server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920030558_AddWatchedRepos")]
    partial class AddWatchedRepos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCharInfo.server.Models.AcceptanceState", b =>
                {
                    b.Property<int>("AcceptanceStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcceptanceStateId"));

                    b.Property<string>("AcceptanceStateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AcceptanceStateId");

                    b.ToTable("AcceptanceStates");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ActionLog", b =>
                {
                    b.Property<int>("ActionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionLogId"));

                    b.Property<int>("AcceptanceStateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActionLogId");

                    b.HasIndex("AcceptanceStateId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModderId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Problematic")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("ApplicationUser", (string)null);
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("VanillaCharInternalName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("ArticleId");

                    b.HasIndex("VanillaCharInternalName");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.BannerImage", b =>
                {
                    b.Property<int>("BannerImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BannerImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("BannerImageId");

                    b.ToTable("BannerImages");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlogPostId"));

                    b.Property<string>("BlogImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("BlogText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlogPostId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.CompatibilityReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("boolean");

                    b.Property<int>("MovesetId1")
                        .HasColumnType("integer");

                    b.Property<int>("MovesetId2")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("MovesetId2");

                    b.HasIndex("UserId");

                    b.HasIndex("MovesetId1", "MovesetId2", "UserId")
                        .IsUnique();

                    b.ToTable("CompatibilityReports");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Dependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DependencyId"));

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DependencyId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.Property<int>("HookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HookId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HookableStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("HookId");

                    b.HasIndex("HookableStatusId");

                    b.HasIndex("Offset")
                        .IsUnique();

                    b.ToTable("Hooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.HookableStatus", b =>
                {
                    b.Property<int>("HookableStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HookableStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("HookableStatusId");

                    b.ToTable("HookableStatus");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeId"));

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 5,
                            ItemTypeName = "Plugin"
                        });
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.Property<int>("ModderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModderId"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("BlueskyHandle")
                        .HasColumnType("text");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<int?>("GamebananaId")
                        .HasColumnType("integer");

                    b.Property<string>("GithubUsername")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUsername")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ModderId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Modders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.Property<int>("MovesetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovesetId"));

                    b.Property<bool?>("AdminPick")
                        .HasColumnType("boolean");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("GamebananaWipId")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasAgentInit")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCharacterOpff")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOnLineEnd")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOnLinePre")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOpff")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsJokeMoveset")
                        .HasColumnType("boolean");

                    b.Property<string>("ModPageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModdedCharName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ModpackName")
                        .HasColumnType("text");

                    b.Property<string>("ModsWikiLink")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MovesetHeroImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("PrivateModder")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PrivateMoveset")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReleaseStateId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplacementId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotsEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotsStart")
                        .HasColumnType("integer");

                    b.Property<string>("SlottedId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThumbhImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VanillaCharInternalName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("MovesetId");

                    b.HasIndex("ReleaseStateId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("VanillaCharInternalName");

                    b.ToTable("Movesets");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetAdminNote", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("MovesetId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("MovesetAdminNotes");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetArticle", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ModdedName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("MovesetArticles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetDependency", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("MovesetDependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetEditor", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("ModderId")
                        .HasColumnType("integer");

                    b.Property<bool>("FullAccess")
                        .HasColumnType("boolean");

                    b.HasKey("MovesetId", "ModderId");

                    b.HasIndex("ModderId");

                    b.ToTable("MovesetEditors");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetHook", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("HookId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "HookId");

                    b.HasIndex("HookId");

                    b.ToTable("MovesetHooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetLike", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MovesetId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MovesetLikes");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetModder", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("ModderId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "ModderId");

                    b.HasIndex("ModderId");

                    b.ToTable("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Plugin", b =>
                {
                    b.Property<int>("PluginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PluginId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLearnMoreUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("DependencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("OwnerModderId")
                        .HasColumnType("integer");

                    b.HasKey("PluginId");

                    b.HasIndex("DependencyId");

                    b.HasIndex("MovesetId");

                    b.HasIndex("OwnerModderId");

                    b.ToTable("Plugins", t =>
                        {
                            t.HasCheckConstraint("CK_Plugin_SingleAttachment", "(CASE WHEN \"MovesetId\" IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN \"DependencyId\" IS NOT NULL THEN 1 ELSE 0 END) <= 1");
                        });
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.PluginVersion", b =>
                {
                    b.Property<int>("PluginVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PluginVersionId"));

                    b.Property<int>("CheckCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnMoreUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PluginId")
                        .HasColumnType("integer");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("PluginVersionId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("PluginId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("PluginVersions");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ReleaseState", b =>
                {
                    b.Property<int>("ReleaseStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReleaseStateId"));

                    b.Property<string>("ReleaseStateName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReleaseStateId");

                    b.ToTable("ReleaseStates");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("SeriesIconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("SeriesId");

                    b.HasIndex("SeriesName")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UnknownPluginHash", b =>
                {
                    b.Property<int>("UnknownPluginHashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnknownPluginHashId"));

                    b.Property<int>("CheckCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UnknownPluginHashId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("UnknownPluginHashes");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserIpAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IpAddress")
                        .IsUnique();

                    b.ToTable("UserIpAddresses");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.VanillaChar", b =>
                {
                    b.Property<string>("VanillaCharInternalName")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.HasKey("VanillaCharInternalName");

                    b.ToTable("VanillaChars");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.WatchedRepo", b =>
                {
                    b.Property<int>("WatchedRepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchedRepoId"));

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WatchedRepoId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("Owner", "Repo")
                        .IsUnique();

                    b.ToTable("WatchedRepos");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ActionLog", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.AcceptanceState", "AcceptanceState")
                        .WithMany("ActionLogs")
                        .HasForeignKey("AcceptanceStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ItemType", "ItemType")
                        .WithMany("ActionLogs")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptanceState");

                    b.Navigation("ItemType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.VanillaChar", "VanillaChar")
                        .WithMany()
                        .HasForeignKey("VanillaCharInternalName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VanillaChar");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.BlogPost", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.CompatibilityReport", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Moveset", null)
                        .WithMany()
                        .HasForeignKey("MovesetId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", null)
                        .WithMany()
                        .HasForeignKey("MovesetId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.HookableStatus", "HookableStatus")
                        .WithMany("Hooks")
                        .HasForeignKey("HookableStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HookableStatus");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithOne("Modder")
                        .HasForeignKey("CustomCharInfo.server.Models.Modder", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ReleaseState", "ReleaseState")
                        .WithMany()
                        .HasForeignKey("ReleaseStateId");

                    b.HasOne("CustomCharInfo.server.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("CustomCharInfo.server.Models.VanillaChar", "VanillaChar")
                        .WithMany()
                        .HasForeignKey("VanillaCharInternalName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseState");

                    b.Navigation("Series");

                    b.Navigation("VanillaChar");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetAdminNote", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Moveset", null)
                        .WithMany()
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetArticle", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Article", "Article")
                        .WithMany("MovesetArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetArticles")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetDependency", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Dependency", "Dependency")
                        .WithMany("MovesetDependencies")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetDependencies")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetEditor", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Modder", "Modder")
                        .WithMany()
                        .HasForeignKey("ModderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetEditors")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modder");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetHook", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Hook", "Hook")
                        .WithMany("MovesetHooks")
                        .HasForeignKey("HookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetHooks")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hook");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetLike", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany()
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moveset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetModder", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Modder", "Modder")
                        .WithMany("MovesetModders")
                        .HasForeignKey("ModderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetModders")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modder");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Plugin", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Dependency", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany()
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CustomCharInfo.server.Models.Modder", "OwnerModder")
                        .WithMany()
                        .HasForeignKey("OwnerModderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Moveset");

                    b.Navigation("OwnerModder");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.PluginVersion", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Plugin", "Plugin")
                        .WithMany("PluginVersions")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plugin");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.RefreshToken", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserIpAddress", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.WatchedRepo", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.AcceptanceState", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.Navigation("Modder");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.Navigation("MovesetArticles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Dependency", b =>
                {
                    b.Navigation("MovesetDependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.Navigation("MovesetHooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.HookableStatus", b =>
                {
                    b.Navigation("Hooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ItemType", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.Navigation("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.Navigation("MovesetArticles");

                    b.Navigation("MovesetDependencies");

                    b.Navigation("MovesetEditors");

                    b.Navigation("MovesetHooks");

                    b.Navigation("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Plugin", b =>
                {
                    b.Navigation("PluginVersions");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
