// <auto-generated />
using System;
using CustomCharInfo.server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomCharInfo.server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908174511_AddHookItemType")]
    partial class AddHookItemType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCharInfo.server.Models.AcceptanceState", b =>
                {
                    b.Property<int>("AcceptanceStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcceptanceStateId"));

                    b.Property<string>("AcceptanceStateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AcceptanceStateId");

                    b.ToTable("AcceptanceStates");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ActionLog", b =>
                {
                    b.Property<int>("ActionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionLogId"));

                    b.Property<int>("AcceptanceStateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActionLogId");

                    b.HasIndex("AcceptanceStateId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModderId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Problematic")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("ApplicationUser", (string)null);
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("VanillaCharInternalName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("ArticleId");

                    b.HasIndex("VanillaCharInternalName");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlogPostId"));

                    b.Property<string>("BlogImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("BlogText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlogPostId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.CompatibilityReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("boolean");

                    b.Property<int>("MovesetId1")
                        .HasColumnType("integer");

                    b.Property<int>("MovesetId2")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("MovesetId1");

                    b.HasIndex("MovesetId2");

                    b.HasIndex("UserId");

                    b.ToTable("CompatibilityReports");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Dependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DependencyId"));

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DependencyId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.Property<int>("HookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HookId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HookableStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("HookId");

                    b.HasIndex("HookableStatusId");

                    b.ToTable("Hooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.HookableStatus", b =>
                {
                    b.Property<int>("HookableStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HookableStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("HookableStatusId");

                    b.ToTable("HookableStatus");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeId"));

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.Property<int>("ModderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModderId"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("BlueskyHandle")
                        .HasColumnType("text");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<int?>("GamebananaId")
                        .HasColumnType("integer");

                    b.Property<string>("GithubUsername")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PfpUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUsername")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ModderId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Modders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.Property<int>("MovesetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovesetId"));

                    b.Property<bool?>("AdminPick")
                        .HasColumnType("boolean");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("GamebananaWipId")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasAgentInit")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCharacterOpff")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOnLineEnd")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOnLinePre")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlobalOpff")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsJokeMoveset")
                        .HasColumnType("boolean");

                    b.Property<string>("ModPageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModdedCharName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ModpackName")
                        .HasColumnType("text");

                    b.Property<string>("ModsWikiLink")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MovesetHeroImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("PrivateModder")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PrivateMoveset")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReleaseStateId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplacementId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotsEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotsStart")
                        .HasColumnType("integer");

                    b.Property<string>("SlottedId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceCode")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThumbhImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VanillaCharInternalName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("MovesetId");

                    b.HasIndex("ReleaseStateId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("VanillaCharInternalName");

                    b.ToTable("Movesets");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetArticle", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ModdedName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("MovesetArticles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetDependency", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("MovesetDependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetHook", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("HookId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "HookId");

                    b.HasIndex("HookId");

                    b.ToTable("MovesetHooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetLike", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MovesetId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MovesetLikes");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetModder", b =>
                {
                    b.Property<int>("MovesetId")
                        .HasColumnType("integer");

                    b.Property<int>("ModderId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MovesetId", "ModderId");

                    b.HasIndex("ModderId");

                    b.ToTable("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ReleaseState", b =>
                {
                    b.Property<int>("ReleaseStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReleaseStateId"));

                    b.Property<string>("ReleaseStateName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReleaseStateId");

                    b.ToTable("ReleaseStates");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("SeriesIconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("SeriesId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.VanillaChar", b =>
                {
                    b.Property<string>("VanillaCharInternalName")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.HasKey("VanillaCharInternalName");

                    b.ToTable("VanillaChars");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ActionLog", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.AcceptanceState", "AcceptanceState")
                        .WithMany("ActionLogs")
                        .HasForeignKey("AcceptanceStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ItemType", "ItemType")
                        .WithMany("ActionLogs")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptanceState");

                    b.Navigation("ItemType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.VanillaChar", "VanillaChar")
                        .WithMany()
                        .HasForeignKey("VanillaCharInternalName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VanillaChar");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.BlogPost", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.CompatibilityReport", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Moveset", null)
                        .WithMany()
                        .HasForeignKey("MovesetId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", null)
                        .WithMany()
                        .HasForeignKey("MovesetId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.HookableStatus", "HookableStatus")
                        .WithMany("Hooks")
                        .HasForeignKey("HookableStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HookableStatus");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithOne("Modder")
                        .HasForeignKey("CustomCharInfo.server.Models.Modder", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ReleaseState", "ReleaseState")
                        .WithMany()
                        .HasForeignKey("ReleaseStateId");

                    b.HasOne("CustomCharInfo.server.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("CustomCharInfo.server.Models.VanillaChar", "VanillaChar")
                        .WithMany()
                        .HasForeignKey("VanillaCharInternalName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseState");

                    b.Navigation("Series");

                    b.Navigation("VanillaChar");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetArticle", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Article", "Article")
                        .WithMany("MovesetArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetArticles")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetDependency", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Dependency", "Dependency")
                        .WithMany("MovesetDependencies")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetDependencies")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetHook", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Hook", "Hook")
                        .WithMany("MovesetHooks")
                        .HasForeignKey("HookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetHooks")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hook");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetLike", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany()
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moveset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.MovesetModder", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.Modder", "Modder")
                        .WithMany("MovesetModders")
                        .HasForeignKey("ModderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCharInfo.server.Models.Moveset", "Moveset")
                        .WithMany("MovesetModders")
                        .HasForeignKey("MovesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modder");

                    b.Navigation("Moveset");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.RefreshToken", b =>
                {
                    b.HasOne("CustomCharInfo.server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.AcceptanceState", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ApplicationUser", b =>
                {
                    b.Navigation("Modder");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Article", b =>
                {
                    b.Navigation("MovesetArticles");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Dependency", b =>
                {
                    b.Navigation("MovesetDependencies");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Hook", b =>
                {
                    b.Navigation("MovesetHooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.HookableStatus", b =>
                {
                    b.Navigation("Hooks");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.ItemType", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Modder", b =>
                {
                    b.Navigation("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.Moveset", b =>
                {
                    b.Navigation("MovesetArticles");

                    b.Navigation("MovesetDependencies");

                    b.Navigation("MovesetHooks");

                    b.Navigation("MovesetModders");
                });

            modelBuilder.Entity("CustomCharInfo.server.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
