<template>
  <v-menu open-on-hover :open-delay="150" :close-on-content-click="false" location="bottom">
    <template #activator="{ props: menuProps }">
      <StatusTag
        v-bind="{ ...menuProps, ...$attrs }"
        :offset-state="entry.offsetStateId"
        class="offset-pill"
        tabindex="0"
      />
    </template>

    <div class="panel pill-card">
      <p class="pill-text">{{ explanation }}</p>
      <p v-if="!isConfirmed && canConfirm" class="pill-text">
        Checked it in {{ entry.gameVersion }} yourself? Confirm it so other modders know it is
        right, or open the hook to correct it.
      </p>
      <p v-else-if="!isConfirmed" class="pill-text">
        A modder who has checked it in the game can confirm it from here.
      </p>
      <div v-if="!isConfirmed && canConfirm" class="pill-actions">
        <AppButton size="sm" variant="primary" icon="mdi-check" :busy="saving" @click="confirm">
          Confirm for {{ entry.gameVersion }}
        </AppButton>
      </div>
    </div>
  </v-menu>
</template>

<script setup>
import { ref, computed } from 'vue'
import { format } from 'date-fns'
import api from '@/services/api'
import { useNotify } from '@/composables/useNotify'
import { OffsetState } from '@/globals'
import StatusTag from '@/components/StatusTag.vue'
import AppButton from '@/components/AppButton.vue'

// A hook offset's state as a tag. Hovering explains how the offset came to be;
// modders can confirm an unverified one without leaving the page.
// Attributes such as a margin class go on the tag itself, not on the menu that wraps it.
defineOptions({ inheritAttrs: false })

const props = defineProps({
  entry: { type: Object, required: true },
  hookId: { type: Number, required: true },
  canConfirm: { type: Boolean, default: false },
})
const emit = defineEmits(['confirmed'])

const notify = useNotify()
const saving = ref(false)

const isConfirmed = computed(() => props.entry.offsetStateId === OffsetState.Confirmed)

const explanation = computed(() => {
  const version = props.entry.gameVersion
  switch (props.entry.offsetStateId) {
    case OffsetState.Confirmed:
      return `Confirmed for ${version} on ${format(new Date(props.entry.updatedAt), 'PP')}.`
    case OffsetState.Generated:
      return `Autogenerated for ${version}, but it's unconfirmed whether it's correct.`
    case OffsetState.CarriedForward:
      return `Autogenerated for ${version}, but it's unconfirmed whether it's correct.`
    default:
      return ''
  }
})

const confirm = async () => {
  saving.value = true
  try {
    const res = await api.put(`/hooks/${props.hookId}/offsets/${props.entry.gameVersionId}`, {})
    notify.success(`Offset confirmed for ${props.entry.gameVersion}.`)
    emit('confirmed', res.data)
  } catch (err) {
    if (err.response?.status === 409 || err.response?.status === 400) {
      notify.warning(err.response.data)
    } else {
      notify.error('Failed to confirm the offset.', err)
    }
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.offset-pill {
  cursor: help;
}

.pill-card {
  max-width: 360px;
  padding: 14px 16px;
  border-color: var(--line-2);
}

.pill-text {
  margin: 0;
  font-size: 13.5px;
  line-height: 1.45;
}

.pill-text + .pill-text {
  margin-top: 8px;
}

.pill-actions {
  display: flex;
  justify-content: flex-end;
  margin-top: 12px;
}
</style>
