<template>
  <v-menu open-on-hover :open-delay="150" :close-on-content-click="false" location="bottom">
    <template #activator="{ props: menuProps }">
      <span
        v-bind="{ ...menuProps, ...$attrs }"
        class="offset-pill"
        :class="`offset-state-${entry.offsetStateId}`"
        tabindex="0"
      >
        {{ OFFSET_STATE_NAMES[entry.offsetStateId] || entry.offsetState }}
      </span>
    </template>

    <v-card color="#262626" max-width="360px" class="pill-card">
      <v-card-text class="pill-text">
        <p>{{ explanation }}</p>
        <p v-if="!isConfirmed && canConfirm" class="mt-2">
          Checked it in {{ entry.gameVersion }} yourself? Confirm it so other modders know it is
          right, or open the hook to correct it.
        </p>
        <p v-else-if="!isConfirmed" class="mt-2">
          A modder who has checked it in the game can confirm it from here.
        </p>
      </v-card-text>
      <v-card-actions v-if="!isConfirmed && canConfirm">
        <v-spacer />
        <v-btn size="small" class="confirm-button" :loading="saving" @click="confirm">
          Confirm for {{ entry.gameVersion }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-menu>
</template>

<script setup>
import { ref, computed } from 'vue'
import { format } from 'date-fns'
import api from '@/services/api'
import { useNotify } from '@/composables/useNotify'
import { OffsetState, OFFSET_STATE_NAMES } from '@/globals'

// A hook offset's state as a pill. Hovering explains how the offset came to be;
// modders can confirm an unverified one without leaving the page.
// Attributes such as a margin class go on the pill itself, not on the menu that wraps it.
defineOptions({ inheritAttrs: false })

const props = defineProps({
  entry: { type: Object, required: true },
  hookId: { type: Number, required: true },
  canConfirm: { type: Boolean, default: false },
})
const emit = defineEmits(['confirmed'])

const notify = useNotify()
const saving = ref(false)

const isConfirmed = computed(() => props.entry.offsetStateId === OffsetState.Confirmed)

const explanation = computed(() => {
  const version = props.entry.gameVersion
  switch (props.entry.offsetStateId) {
    case OffsetState.Confirmed:
      return `Confirmed for ${version} on ${format(new Date(props.entry.updatedAt), 'PP')}.`
    case OffsetState.Generated:
      return `Autogenerated for ${version}, but it's unconfirmed whether it's correct.`
    case OffsetState.CarriedForward:
      return `Autogenerated for ${version}, but it's unconfirmed whether it's correct.`
    default:
      return ''
  }
})

const confirm = async () => {
  saving.value = true
  try {
    const res = await api.put(`/hooks/${props.hookId}/offsets/${props.entry.gameVersionId}`, {})
    notify.success(`Offset confirmed for ${props.entry.gameVersion}.`)
    emit('confirmed', res.data)
  } catch (err) {
    if (err.response?.status === 409 || err.response?.status === 400) {
      notify.warning(err.response.data)
    } else {
      notify.error('Failed to confirm the offset.', err)
    }
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.offset-pill {
  display: inline-block;
  padding: 1px 7px;
  border-radius: 10px;
  font-size: 0.7rem;
  font-weight: 500;
  white-space: nowrap;
  vertical-align: middle;
  cursor: help;
}
.offset-state-1 {
  background-color: #2e7d32;
  color: white;
}
.offset-state-2 {
  background-color: #fbc02d;
  color: black;
}
.offset-state-3 {
  background-color: #ef6c00;
  color: white;
}

.pill-text {
  font-size: 0.85rem;
  line-height: 1.4;
}

.confirm-button {
  background-color: #2e7d32;
  color: white;
  text-transform: none;
}
</style>
