using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomCharInfo.server.Models
{
    // How a hook's offset for one game version was determined. Whether entered or confirmed by a modder or automatically generated by the site.
    [Table("OffsetState")]
    public class OffsetState
    {
        [Key]
        public int OffsetStateId { get; set; }

        [Required, MaxLength(32)]
        public string Name { get; set; }

        public ICollection<HookOffset> HookOffsets { get; set; }
    }
}
